---
logger:
    logSubfolder: "logs"
    logFilename: "logs.log"
    logFormat: "[%(asctime)s][%(levelname)s][%(threadName)s][%(module)s][Line %(lineno)d] %(message)s"
---
goProHero10:
    #https://gopro.github.io/OpenGoPro/http#section/Setup
    serialNr: "C3464280021547"
    serialNrX: 5
    serialNrY: 4
    serialNrZ: 7

---
camera: 
    enableDirectShow: true
    showFPS: true
    imageSubfolder: images #subfolder of the output images
    frameWidth: 800
    frameHeight: 600
...